DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS delivery CASCADE;
DROP TABLE IF EXISTS review CASCADE;
DROP TABLE IF EXISTS order_item CASCADE;
DROP TABLE IF EXISTS food_order CASCADE;
DROP TABLE IF EXISTS menu_item CASCADE;
DROP TABLE IF EXISTS restaurant_delivery_area CASCADE;
DROP TABLE IF EXISTS client CASCADE;
DROP TABLE IF EXISTS menu CASCADE;
DROP TABLE IF EXISTS restaurant CASCADE;
DROP TABLE IF EXISTS owner CASCADE;
DROP TABLE IF EXISTS restaurant_address CASCADE;
DROP TABLE IF EXISTS food_ordering_app_user CASCADE;
DROP TABLE IF EXISTS restaurant_delivery_street CASCADE;

DROP TABLE IF EXISTS flyway_schema_history CASCADE;